export const CHANGE_VIEW = 'CHANGE_VIEW';

// SideBar
export const CHANGE_CENSUS_DIVISION = 'CHANGE_CENSUS_DIVISION';
export const CHANGE_DEMOGRAPHIC = 'CHANGE_DEMOGRAPHIC';
export const CHANGE_OPERATING_BUDGET = "CHANGE_OPERATING_BUDGET";
export const CHANGE_CLIENT_SERVED = "CHANGE_CLIENT_SERVED";
export const CHANGE_STAFF_COUNT = "CHANGE_STAFF_COUNT";