export const CHANGE_VIEW = 'CHANGE_VIEW';

// SideBar
export const CHANGE_CENSUS_DIVISION   = 'CHANGE_CENSUS_DIVISION';
export const CHANGE_DEMOGRAPHIC       = 'CHANGE_DEMOGRAPHIC';
export const CHANGE_OPERATING_BUDGET  = 'CHANGE_OPERATING_BUDGET';
export const CHANGE_CLIENT_SERVED     = 'CHANGE_CLIENT_SERVED';
export const CHANGE_STAFF_COUNT       = 'CHANGE_STAFF_COUNT';

// auth
export const SIGN_IN = 'SIGN_IN';

// thunks
export const LOAD_SERVICE_PROVIDERS = 'LOAD_SERVICE_PROVIDERS'
export const LOAD_CENSUS_DIVISION_DATA = 'LOAD_CENSUS_DIVISION_DATA'

// Map
export const SELECT_CENSUS_DIVISION = "SELECT_CENSUS_DIVISION";
export const LOAD_DEMOGRAPHICS = 'LOAD_DEMOGRAPHICS';
